case 0x20: {pc.w += 2;COND_JR(!(af.b.l & F_Z),m.read_byte(pc.w - 1));break;}
case 0x28: {pc.w += 2;COND_JR((af.b.l & F_Z),m.read_byte(pc.w - 1));break;}
case 0x30: {pc.w += 2;COND_JR(!(af.b.l & F_C),m.read_byte(pc.w - 1));break;}
case 0x38: {pc.w += 2;COND_JR((af.b.l & F_C),m.read_byte(pc.w - 1));break;}
case 0xc0: {pc.w += 1;COND_RET(!(af.b.l & F_Z));break;}
case 0xc2: {pc.w += 3;COND_JP(!(af.b.l & F_Z),m.read_word(pc.w - 2));break;}
case 0xc4: {pc.w += 3;COND_CALL(!(af.b.l & F_Z),m.read_word(pc.w - 2));break;}
case 0xc8: {pc.w += 1;COND_RET((af.b.l & F_Z));break;}
case 0xca: {pc.w += 3;COND_JP((af.b.l & F_Z),m.read_word(pc.w - 2));break;}
case 0xcc: {pc.w += 3;COND_CALL((af.b.l & F_Z),m.read_word(pc.w - 2));break;}
case 0xd0: {pc.w += 1;COND_RET(!(af.b.l & F_C));break;}
case 0xd2: {pc.w += 3;COND_JP(!(af.b.l & F_C),m.read_word(pc.w - 2));break;}
case 0xd4: {pc.w += 3;COND_CALL(!(af.b.l & F_C),m.read_word(pc.w - 2));break;}
case 0xd8: {pc.w += 1;COND_RET((af.b.l & F_C));break;}
case 0xda: {pc.w += 3;COND_JP((af.b.l & F_C),m.read_word(pc.w - 2));break;}
case 0xdc: {pc.w += 3;COND_CALL((af.b.l & F_C),m.read_word(pc.w - 2));break;}
